subset(planetas_df,diametro<1)
posiciones<-order(planetas_df$diametro)
planetas_df[posiciones,]
####
Died.At<-c(22,40,72,41)
Writer.At<-c(16,18,36,36)
Fist.name<-c("Jhon","Edgar","Walt","Jane")
Second.name<-c("Doe","Poe","Whitman","Dostin")
sexo<-c("Male","Male","Male","Female")
date.of.death<-c("2015-05-10","1849-10-07","1982-03-26","1817-07-18")
writers_df<-data.frame(Died.At,Writer.At,Fist.name,Second.name,sexo,date.of.death)
help("as.Date")
writers_df<-data.frame(Died.At,Writer.At,I(Fist.name),I(Second.name),sexo,as.Date(date.of.death,"%Y-%m-%d"))
View(writers_df)
names(writers_df)<-c("age.of.death","age.as.writer","name","surname","gender","death")
row.names(writers_df)<-c("Id1","Id2","Id3","Id4")
dim(writers_df) ##dimension
nrow(writers_df)
ncol(writers_df)
length(writers_df)
ages<-writers_df[,1:2]
apply(ages,2,median)
apply(ages,1,median)
apply(ages,2,mean)
###
ab<-data.frame()
View(ab)
age<-numeric()
nombre<-character()
identificacion<-integer()
genero<-factor()
fecha<-as.Date(character())
ab<-data.frame(age,nombre,identificacion,genero,fecha)
View(ab)
ab$age<-c(52,45,12,89,16)
writer_names<-writers_df[1:4,c("name","surname")]
str(writer_names)
name_writer<-subset(writers_df,Fist.name=="Jane")
forty_writers<-writers_df[grep("4",writers_df$Died.At),]
writers_df$Died.At<-NULL
writers_df[1,3]<-NA
filas_a_mantener<-c(F,T,F,T)
limited_writers<-writers_df[filas_a_mantener,]
View(limited_writers)

